[build]
base = "/"
command = "npm run build"
publish = "web/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[build.environment]
NODE_VERSION = "18"
CARGO_HOME = "/opt/buildhome/.cargo"
RUSTUP_HOME = "/opt/buildhome/.rustup"
PATH = "/opt/buildhome/.cargo/bin:$PATH"

[[build.cache]]
paths = ["core/target", "/opt/buildhome/.cargo"]
